title: "Amy Chen"
logo: "/images/Profile photo.jpg"
description: >
  Hi, I'm Amy. I'm currently pursuing my master's degree in Information Systems with a focus on AI, data analytics, and product development.
  <br><br>
   
  <br><br>
  <a href="https://www.linkedin.com/in/amy-ching-yang-chen/" target="_blank">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal

show_downloads: false
google_analytics: ""  # Add your GA tracking ID if needed, e.g., "UA-XXXXXXXXX-X"
author:
  name: "Amy Chen"
  email: "chingyang1025@gmail.com"

# Build settings
markdown: kramdown
